name: Lua Rocks package

on:
  push:
    tags:
       - '*'

jobs:
  upload_rockspec:
    name: Check Lua lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Luarocks
        run: |
          sudo apt update && sudo apt install -y luarocks
      - name: Install dkjson
        run: |
          sudo luarocks install dkjson
      - name: Set environment variables
        id: set_env
        run: |
          echo "::set-output name=VERSION_LUAROCKS::0.2-0"
          echo "::set-output name=SRC_TAG::0.2-0"
      - name: Prepare rockspec
        run: |
          sed -i "s/VERSION_LUAROCKS/${{ steps.set_env.VERSION_LUAROCKS }}/g" nginx-lua-exporter.rockspec  && \
          sed -i "s/SRC_TAG/${{ steps.set_env.SRC_TAG }}/g" nginx-lua-exporter.rockspec  && \
          mv nginx-lua-exporter.rockspec nginx-lua-exporter-${{ steps.set_env.VERSION_LUAROCKS }}.rockspec &&
          cat  nginx-lua-exporter-${{ steps.set_env.VERSION_LUAROCKS }}.rockspec
      - name: Upload rockspec
        env:
          API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        run: |
          sudo luarocks upload --api-key="$API_KEY" --force nginx-lua-exporter-${{ steps.set_env.VERSION_LUAROCKS }}.rockspec